include:
   - ${WS_SERVER}/docker-networks.yml
services:
  smtp:
    image: boky/postfix:latest
    container_name: server-smtp
    restart: unless-stopped
    environment:
      - HOSTNAME=mail.linksize.com                  # # reverse DNS ile aynı olsun (deliverability için önemli)
      - ALLOWED_SENDER_DOMAINS=linksize.com         # buraya kendi domain(ler)ini yaz, birden fazlaysa boşlukla ayır: linksize.com site2.com  # İstersen ek kısıtlamasız yap (ama önerilmez): - ALLOW_EMPTY_SENDER_DOMAINS=true
      - DKIM_AUTOGENERATE=true                      # ← bu satırı ekle (veya 1 yazabilirsin)
      - DKIM_SELECTOR=smtp                          # ← opsiyonel, default "mail" zaten ama belirtmek iyi (selector adı)
    networks:
      - web
    # Eğer kalıcı anahtar istiyorsan (restart'ta kaybolmasın), volume ekle:
    volumes:
      - ./smtp/dkim-keys:/etc/opendkim/keys              # host'ta ./dkim-keys klasörü oluştur, container üretince buraya kaydeder



